baseurl         = "https://rguske.github.io/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 12
SectionPagesMenu = "main"
canonifyurls    = true
enableEmoji     = true

[params]
  title       = "Robert Guske"
  subtitle    = '"Sometimes you gotta run before you can walk!"'
  subsubtitle = 'Anthony Edward "Tony" Stark, also known as IRON MAN'
  copyright   = "© All rights reserved -2018"

  cover       = "img/blog_cover_usercon.jpeg"
  description = "rguske.github.io is a personal website which provides informational & detailed content, based on Robert Guske´s gained experiences with solutions by VMware (primarily)."
  metaDescription = "Only IT related content, topics are primarily Cloud-Native & VMware solutions oriented, I try not to write posts boringly."
  googleAnalytics = "UA-122353302-1"
  customCSS = ["dist/css/tagformatting.css"]
  RSSLink = ""

  twitterName = "vmw_rguske"
  # fbName = "fakeghost"
  githubName = "rguske"
  linkedinName = "robert-guske-830853111"
  # mediumName = ""

  # logo = "hugo-logo.png"
  # orgName = "EM"
  # orgWebsite = "https://www.telematika.org"
  # orgDescription = "Here is a description placeholder for your org"

  showSupport = false

  author = "Robert Guske"
  authorAvatar = "img/profile_robert.jpg"
  authorLocation = "Hamburg, Germany"
  authorWebsite = "https://rguske.github.io"
  authorDescription = "Robert is an accomplished, hands-on, & well informed IT professional with 15+ years of experience in providing strategic guidance regarding IT technology and infrastructural enhancements to clients and organizations."

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "caspertwo"

[permalinks]
  posts = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "About Me"
  url = "/about"
  weight = 100

#[[menu.main]]
# name = "Post"
# url = "/post"
# weight = 100

#[[menu.main]]
#  name = "Tags"
#  url = "/tags"
#  weight = 98

[[menu.main]]
  name = "VMware Microsites"
  url = "/post/vmware-microsites-you-should-bookmark"
  weight = 97

[[menu.main]]
  name = "Github Repo"
  url = "https://github.com/rguske"
  weight = 96

  [[menu.main]]
  name = "Disclaimer"
  url = "/disclaimer"
  weight = 95