baseurl         = "https://rguske.github.io/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 12
SectionPagesMenu = "main"
canonifyurls    = true
enableEmoji     = true

[params]
  title       = "j.a.r.v.i.s."
  subtitle    = "Sometimes you gotta run before you can walk!"
  copyright   = "© All rights reserved -2018"

  cover       = "img/blog-cover.jpg"
  description = "Here is a description of your site."
  metaDescription = ""
  googleAnalytics = "UA-122353302-1"
  customCSS = []
  RSSLink = ""

  twitterName = "vmw_rguske"
  # fbName = "fakeghost"
  githubName = "rguske"
  linkedinName = "robert-guske-830853111"
  # mediumName = ""

  # logo = "hugo-logo.png"
  # orgName = "EM"
  # orgWebsite = "https://www.telematika.org"
  # orgDescription = "Here is a description placeholder for your org"

  showSupport = false

  author = "Robert Guske"
  authorAvatar = "img/profile_robert.jpg"
  authorLocation = "Hamburg, Germany"
  authorWebsite = "https://rguske.github.io"
  authorDescription = "Read more."

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "caspertwo"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "About Me"
  url = "/about"
  weight = 100

# [[menu.main]]
#  name = "Post"
#  url = "/post/post"
#  weight = 100

[[menu.main]]
  name = "Disclaimer"
  url = "/disclaimer"
  weight = 99

[[menu.main]]
  name = "Tags"
  url = "/tags"
  weight = 98

[[menu.main]]
  name = "vic-machine examples"
  url = "https://github.com/rguske/vic-machine"
  weight = 97

[[menu.main]]
  name = "VMware´s Offical CNA Blog"
  url = "https://blogs.vmware.com/cloudnative/"
  weight = 96